### ISSUE TITLE
fix exception upon creating an invitation on a renku that already has an open invitation

### ISSUE THREAD

**Issue by dewalor** [dewalor/linku#2]
2024-03-28T05:27:41Z app[17811020c509d8] mia [info]Request: GET /home
2024-03-28T05:27:41Z app[17811020c509d8] mia [info]** (exit) an exception was raised:
2024-03-28T05:27:41Z app[17811020c509d8] mia [info]    ** (Ecto.MultipleResultsError) expected at most one result but got 2 in query:
2024-03-28T05:27:41Z app[17811020c509d8] mia [info]from i0 in Linku.Collaborations.Invitation,
2024-03-28T05:27:41Z app[17811020c509d8] mia [info]  join: l1 in Linku.Notebooks.Line,
2024-03-28T05:27:41Z app[17811020c509d8] mia [info]  on: l1.id == i0.line_id,
2024-03-28T05:27:41Z app[17811020c509d8] mia [info]  where: l1.renku_id == ^5 and is_nil(i0.accepted_at),
2024-03-28T05:27:41Z app[17811020c509d8] mia [info]  select: i0.invitee_email
2024-03-28T05:27:41Z app[17811020c509d8] mia [info]        (ecto 3.10.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
2024-03-28T05:27:41Z app[17811020c509d8] mia [info]        (linku 0.1.0) lib/linku_web/live/renku_component.ex:163: LinkuWeb.RenkuComponent.update/2

Repo.one crashes the server:
  defp update_invitation_if_any(multi, renku, current_user) do
      open_invitation_for_renku_query = from i in Invitation,
      join: l in Line,
      on: l.id == i.line_id,
      where: l.renku_id == ^renku.id,
      where: is_nil(i.accepted_at),
      where: i.invitee_email == ^current_user.email

      invitation = Repo.one(open_invitation_for_renku_query)

**Comment by robotarmy** [comment]
If send two invitations to same email 

triggers this condition.


```Ecto.MultipleResultsError at GET /home
expected at most one result but got 2 in query:

from i0 in Linku.Collaborations.Invitation,
  join: l1 in Linku.Notebooks.Line,
  on: l1.id == i0.line_id,
  where: l1.renku_id == ^2 and is_nil(i0.accepted_at),
  select: i0.invitee_email
# Ecto.MultipleResultsError at GET /home

Exception:

    ** (Ecto.MultipleResultsError) expected at most one result but got 2 in query:
    
    from i0 in Linku.Collaborations.Invitation,
      join: l1 in Linku.Notebooks.Line,
      on: l1.id == i0.line_id,
      where: l1.renku_id == ^2 and is_nil(i0.accepted_at),
      select: i0.invitee_email
    
        (ecto 3.10.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
        (linku 0.1.0) lib/linku_web/live/renku_component.ex:165: LinkuWeb.RenkuComponent.update/2
        (phoenix_live_view 0.19.0) lib/phoenix_live_view/utils.ex:487: Phoenix.LiveView.Utils.maybe_call_update!/3
        (phoenix_live_view 0.19.0) lib/phoenix_live_view/diff.ex:652: anonymous fn/5 in Phoenix.LiveView.Diff.render_pending_components/6
        (elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
        (stdlib 6.1.2) maps.erl:860: :maps.fold_1/4
        (phoenix_live_view 0.19.0) lib/phoenix_live_view/diff.ex:628: Phoenix.LiveView.Diff.render_pending_components/6
        (phoenix_live_view 0.19.0) lib/phoenix_live_view/diff.ex:143: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view 0.19.0) lib/phoenix_live_view/static.ex:252: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view 0.19.0) lib/phoenix_live_view/static.ex:135: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.19.0) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.7.2) lib/phoenix/router.ex:430: Phoenix.Router.__call__/5
        (linku 0.1.0) lib/linku_web/endpoint.ex:1: LinkuWeb.Endpoint.plug_builder_call/2
        (linku 0.1.0) deps/plug/lib/plug/debugger.ex:136: LinkuWeb.Endpoint."call (overridable 3)"/2
        (linku 0.1.0) lib/linku_web/endpoint.ex:1: LinkuWeb.Endpoint.call/2
        (phoenix 1.7.2) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.9.0) /Users/ram9/Hack/linku/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /Users/ram9/Hack/linku/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /Users/ram9/Hack/linku/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
    

Code:

`lib/ecto/repo/queryable.ex`

    149   
    150     def one(name, queryable, tuplet) do
    151       case all(name, queryable, tuplet) do
    152         [one] -> one
    153         [] -> nil
    154>        other -> raise Ecto.MultipleResultsError, queryable: queryable, count: length(other)
    155       end
    156     end
    157   
    158     def one!(name, queryable, tuplet) do
    159       case all(name, queryable, tuplet) do
    
`lib/linku_web/live/renku_component.ex`

    160             renku: renku,
    161             renku_id: renku.id,
    162             max_lines: max_lines,
    163             line_count: line_count,
    164             renku_initiator_id: renku.user_id,
    165>            current_invitee_email: Collaborations.current_invitee_email(renku),
    166             display_invitation_pencil: false,
    167             display_invitations: is_nil(renku.published_at),
    168             show_new_line: line_count < max_lines,
    169             scope: assigns.scope)
    170        |> stream(:lines, line_forms)}
    
`lib/phoenix_live_view/utils.ex`

    482     Calls the optional `update/2` callback, otherwise update the socket directly.
    483     """
    484     def maybe_call_update!(socket, component, assigns) do
    485       if function_exported?(component, :update, 2) do
    486         socket =
    487>          case component.update(assigns, socket) do
    488             {:ok, %Socket{} = socket} ->
    489               socket
    490   
    491             other ->
    492               raise ArgumentError, """
    
`lib/phoenix_live_view/diff.ex`

    647   
    648                   {mount_component(socket, component, myself_assigns),
    649                    put_cid(components, component, id, cid)}
    650               end
    651   
    652>            socket = Utils.maybe_call_update!(socket, component, new_assigns)
    653             diffs = maybe_put_events(diffs, socket)
    654   
    655             triplet =
    656               render_component(socket, component, id, cid, new?, pending, cids, diffs, components)
    657   
    
`lib/enum.ex`

    No code available.

`maps.erl`

    No code available.

`lib/phoenix_live_view/diff.ex`

    623   
    624     defp render_pending_components(socket, pending, seen_ids, cids, diffs, components) do
    625       acc = {{%{}, diffs, components}, seen_ids}
    626   
    627       {{pending, diffs, components}, seen_ids} =
    628>        Enum.reduce(pending, acc, fn {component, entries}, acc ->
    629           entries = maybe_preload_components(component, Enum.reverse(entries))
    630   
    631           Enum.reduce(entries, acc, fn {cid, id, new?, new_assigns}, {triplet, seen_ids} ->
    632             {pending, diffs, components} = triplet
    633   
    
`lib/phoenix_live_view/diff.ex`

    138       # cid_to_component is used by maybe_reuse_static and it must be a copy before changes.
    139       # However, given traverse does not change cid_to_component, we can read it now.
    140       {cid_to_component, _, _} = components
    141   
    142       {cdiffs, components} =
    143>        render_pending_components(socket, pending, cid_to_component, %{}, components)
    144   
    145       socket = %{socket | fingerprints: prints}
    146       diff = maybe_put_title(diff, socket)
    147       {diff, cdiffs} = extract_events({diff, cdiffs})
    148   
    
`lib/phoenix_live_view/static.ex`

    247       Phoenix.HTML.Tag.content_tag(tag, "", attrs)
    248     end
    249   
    250     defp to_rendered_content_tag(socket, tag, view, attrs) do
    251       rendered = Utils.to_rendered(socket, view)
    252>      {_, diff, _} = Diff.render(socket, rendered, Diff.new_components())
    253       Phoenix.HTML.Tag.content_tag(tag, {:safe, Diff.to_iodata(diff)}, attrs)
    254     end
    255   
    256     defp load_live!(view_or_component, kind) do
    257       case view_or_component.__live__() do
    
`lib/phoenix_live_view/static.ex`

    130             {:data, data_attrs}
    131             | extended_attrs
    132           ]
    133   
    134           try do
    135>            {:ok, to_rendered_content_tag(socket, tag, view, attrs), socket.assigns}
    136           catch
    137             :throw, {:phoenix, :child_redirect, redirected, flash} ->
    138               {:stop, Utils.replace_flash(%{socket | redirected: redirected}, flash)}
    139           end
    140   
    
`lib/phoenix_live_view/controller.ex`

    34           end
    35         end
    36   
    37     """
    38     def live_render(%Plug.Conn{} = conn, view, opts \\ []) do
    39>      case LiveView.Static.render(conn, view, opts) do
    40         {:ok, content, socket_assigns} ->
    41           conn
    42           |> Phoenix.Controller.put_view(LiveView.Static)
    43           |> Phoenix.Controller.render(
    44             "template.html",
    
`lib/phoenix/router.ex`

    425           :telemetry.execute([:phoenix, :router_dispatch, :stop], measurements, metadata)
    426           halted_conn
    427   
    428         %Plug.Conn{} = piped_conn ->
    429           try do
    430>            plug.call(piped_conn, plug.init(opts))
    431           else
    432             conn ->
    433               measurements = %{duration: System.monotonic_time() - start}
    434               metadata = %{metadata | conn: conn}
    435               :telemetry.execute([:phoenix, :router_dispatch, :stop], measurements, metadata)
    
`lib/linku_web/endpoint.ex`

    1>  defmodule LinkuWeb.Endpoint do
    2     use Phoenix.Endpoint, otp_app: :linku
    3   
    4     # The session will be stored in the cookie and signed,
    5     # this means its contents can be read but not tampered with.
    6     # Set :encryption_salt if you would also like to encrypt it.
    
`deps/plug/lib/plug/debugger.ex`

    131             case conn do
    132               %Plug.Conn{path_info: ["__plug__", "debugger", "action"], method: "POST"} ->
    133                 Plug.Debugger.run_action(conn)
    134   
    135               %Plug.Conn{} ->
    136>                super(conn, opts)
    137             end
    138           rescue
    139             e in Plug.Conn.WrapperError ->
    140               %{conn: conn, kind: kind, reason: reason, stack: stack} = e
    141               Plug.Debugger.__catch__(conn, kind, reason, stack, @plug_debugger)
    
`lib/linku_web/endpoint.ex`

    1>  defmodule LinkuWeb.Endpoint do
    2     use Phoenix.Endpoint, otp_app: :linku
    3   
    4     # The session will be stored in the cookie and signed,
    5     # this means its contents can be read but not tampered with.
    6     # Set :encryption_salt if you would also like to encrypt it.
    
`lib/phoenix/endpoint/sync_code_reload_plug.ex`

    17   
    18     def call(conn, {endpoint, opts}), do: do_call(conn, endpoint, opts, true)
    19   
    20     defp do_call(conn, endpoint, opts, retry?) do
    21       try do
    22>        endpoint.call(conn, opts)
    23       rescue
    24         exception in [UndefinedFunctionError] ->
    25           case exception do
    26             %UndefinedFunctionError{module: ^endpoint} when retry? ->
    27               # Sync with the code reloader and retry once
    
`lib/plug/cowboy/handler.ex`

    6     def init(req, {plug, opts}) do
    7       conn = @connection.conn(req)
    8   
    9       try do
    10         conn
    11>        |> plug.call(opts)
    12         |> maybe_send(plug)
    13         |> case do
    14           %Plug.Conn{adapter: {@connection, %{upgrade: {:websocket, websocket_args}} = req}} = conn ->
    15             {handler, state, cowboy_opts} = websocket_args
    16             {__MODULE__, copy_resp_headers(conn, req), {handler, state}, cowboy_opts}
    
`/Users/ram9/Hack/linku/deps/cowboy/src/cowboy_handler.erl`

    32   -optional_callbacks([terminate/3]).
    33   
    34   -spec execute(Req, Env) -> {ok, Req, Env}
    35   	when Req::cowboy_req:req(), Env::cowboy_middleware:env().
    36   execute(Req, Env=#{handler := Handler, handler_opts := HandlerOpts}) ->
    37>  	try Handler:init(Req, HandlerOpts) of
    38   		{ok, Req2, State} ->
    39   			Result = terminate(normal, Req2, State, Handler),
    40   			{ok, Req2, Env#{result => Result}};
    41   		{Mod, Req2, State} ->
    42   			Mod:upgrade(Req2, Env, Handler, State);
    
`/Users/ram9/Hack/linku/deps/cowboy/src/cowboy_stream_h.erl`

    301   	end.
    302   
    303   execute(_, _, []) ->
    304   	ok;
    305   execute(Req, Env, [Middleware|Tail]) ->
    306>  	case Middleware:execute(Req, Env) of
    307   		{ok, Req2, Env2} ->
    308   			execute(Req2, Env2, Tail);
    309   		{suspend, Module, Function, Args} ->
    310   			proc_lib:hibernate(?MODULE, resume, [Env, Tail, Module, Function, Args]);
    311   		{stop, _Req2} ->
    
`/Users/ram9/Hack/linku/deps/cowboy/src/cowboy_stream_h.erl`

    290   %% to simplify the debugging of errors. The proc_lib library
    291   %% already adds the stacktrace to other types of exceptions.
    292   -spec request_process(cowboy_req:req(), cowboy_middleware:env(), [module()]) -> ok.
    293   request_process(Req, Env, Middlewares) ->
    294   	try
    295>  		execute(Req, Env, Middlewares)
    296   	catch
    297   		exit:Reason={shutdown, _}:Stacktrace ->
    298   			erlang:raise(exit, Reason, Stacktrace);
    299   		exit:Reason:Stacktrace when Reason =/= normal, Reason =/= shutdown ->
    300   			erlang:raise(exit, {Reason, Stacktrace}, Stacktrace)
    

## Connection details

### Params

    %{}

### Request info

  * URI: http://localhost:4000/home
  * Query string: 

### Headers
  
  * accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
  * accept-encoding: gzip, deflate, br, zstd
  * accept-language: en-US,en;q=0.9
  * connection: keep-alive
  * cookie: _linku_key=SFMyNTY.g3QAAAADbQAAAAtfY3NyZl90b2tlbm0AAAAYcEN5bEVCVU1pWk9NSGt2VnZRN1pBNjlQbQAAAA5saXZlX3NvY2tldF9pZG0AAAA7dXNlcnNfc2Vzc2lvbnM6c0hrRzZ1VERnZ2VyZmVkeFZHd1pKTmtock1wdWhuanQtQThaeHZTamhxMD1tAAAACnVzZXJfdG9rZW5tAAAAILB5Burkw4IHq33ncVRsGSTZIazKboZ47fgPGcb0o4at.u-ntBzMLdUaUSpoRQWkRm8WACDjYXoSCkA8tz0RxrHQ
  * host: localhost:4000
  * referer: http://localhost:4000/
  * sec-ch-ua: "Not(A:Brand";v="99", "Google Chrome";v="133", "Chromium";v="133"
  * sec-ch-ua-mobile: ?0
  * sec-ch-ua-platform: "macOS"
  * sec-fetch-dest: document
  * sec-fetch-mode: navigate
  * sec-fetch-site: same-origin
  * sec-fetch-user: ?1
  * upgrade-insecure-requests: 1
  * user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36

### Session

    %{"_csrf_token" => "pCylEBUMiZOMHkvVvQ7ZA69P", "live_socket_id" => "users_sessions:sHkG6uTDggerfedxVGwZJNkhrMpuhnjt-A8ZxvSjhq0=", "user_token" => <<176, 121, 6, 234, 228, 195, 130, 7, 171, 125, 231, 113, 84, 108, 25, 36, 217, 33, 172, 202, 110, 134, 120, 237, 248, 15, 25, 198, 244, 163, 134, 173>>}

```
